/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 071d76e5c444bd03630a046be27058f0)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MyAgent";
	}
	interface Env {
		SLACK_SIGNING_SECRET: string;
		SLACK_CLIENT_SECRET: string;
		SLACK_CLIENT_ID: string;
		OPENAI_API_KEY: string;
		OPENAI_BASE_URL: string;
		MyAgent: DurableObjectNamespace<import("./src/index").MyAgent>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
