/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 251d58d7714d5e66e13451154b318fce)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "MyAgent" | "DiscordGateway";
  }
  interface Env {
    ANTHROPIC_API_KEY: string;
    OPENAI_API_KEY: string;
    OPENROUTER_API_KEY: string;
    OPENCODE_API_KEY: string;
    MODEL: string;
    CF_API_TOKEN: string;
    DISCORD_APPLICATION_ID: string;
    DISCORD_CLIENT_ID: string;
    DISCORD_CLIENT_SECRET: string;
    DISCORD_PUBLIC_KEY: string;
    DISCORD_BOT_TOKEN: string;
    TAVILY_API_KEY: string;
    AGENT: DurableObjectNamespace<import("./src/index").MyAgent>;
    DISCORD_GATEWAY: DurableObjectNamespace<
      import("./src/index").DiscordGateway
    >;
    AI: Ai;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | "ANTHROPIC_API_KEY"
        | "OPENAI_API_KEY"
        | "OPENROUTER_API_KEY"
        | "OPENCODE_API_KEY"
        | "MODEL"
        | "CF_API_TOKEN"
        | "DISCORD_APPLICATION_ID"
        | "DISCORD_CLIENT_ID"
        | "DISCORD_CLIENT_SECRET"
        | "DISCORD_PUBLIC_KEY"
        | "DISCORD_BOT_TOKEN"
        | "TAVILY_API_KEY"
      >
    > {}
}
