/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: b941f12901aa81a02d093fb78571d66a)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MyAgent" | "DiscordGateway";
	}
	interface Env {
		OPENROUTER_API_KEY: string;
		DISCORD_BOT_TOKEN: string;
		AGENT: DurableObjectNamespace<import("./src/index").MyAgent>;
		DISCORD_GATEWAY: DurableObjectNamespace<import("./src/index").DiscordGateway>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENROUTER_API_KEY" | "DISCORD_BOT_TOKEN">> {}
}
